### ISSUE TITLE
Error con composer

### ISSUE THREAD

**Issue by Aleixenandros** [NeoRazorX/facturascripts#112]
Buenos días,

No hay forma de instalarlo que no sea con composer?

Uso varias versiones de php en el servidor y la del sistema es la 5.4, pero la que le asigno al proyecto de facturascript es la 7.1. EL problema es que composer me coge la 5.4 que es la del sistema y no la que le tengo asignada a este proyecto.

` - This package requires php >=5.6 but your PHP version (5.4.16) does not satisfy that requirement`

**Comment by NeoRazorX** [comment]
Hola, para desarrollo será necesario composer. Cuando esté completado ya ofreceremos un zip con todas las dependencias incluidas.

Mientras tanto puedes instalarlo en otro equipo y copiar las carpetas vendor y node_modules al servidor.

**Comment by Aleixenandros** [comment]
Gracias, solucionada mi duda.
