### ISSUE TITLE
Warning:  mkdir(): File exists in install.php on line 142

### ISSUE THREAD

**Issue by Yopli2k** [NeoRazorX/facturascripts#19]
Hola, si falla la instalación al crear alguna  de las carpetas que se intentan crear, luego es imposible instalar sin acceder al servidor donde está instalado y borrar manualmente las carpetas.

Quizás se debería plantear que si la carpeta ya existe comprobar los permisos y si no existe crearla.

**Comment by NeoRazorX** [comment]
No termino de ver lo que dices. Pero si quieres modifica la función.

**Comment by shawe** [comment]
Creo que eso tenía que ver con esto que añadí en el createFolders:

https://github.com/NeoRazorX/facturascripts/blob/master/install.php#L216
```
// En caso que ya existan previamente, podemos devolver true
    if (is_dir('Plugins') && is_dir('Dinamic') && is_dir('Cache')) {
        return true;
    }
```

Porqué ahora que lo he leído, he ido a mirar si es que no se había aceptado este cambio al final.

De todos modos, a PHP-CS veo que le gusta más que ese tipo de comprobación se haga así:
https://github.com/NeoRazorX/facturascripts/blob/master/Core/Base/PluginManager.php#L125

Porqué siempre que hay un mkdir indica el siguiente mensaje:

> Condition needs to be corrected (invert if needed): '!@mkdir(...) && !is_dir(...)'. 
> This issue is difficult to reproduce, as any of concurrency-related issues. It appears when several processes are attempting to create a directory which is not yet existing, but between is_dir() and mkdir() calls another process already managed to create a directory.
