### ISSUE TITLE
Suggestion to avoid constantly deploy in some cases (mainly assets)

### ISSUE THREAD

**Issue by shawe** [NeoRazorX/facturascripts#384]
With php files this isn't the same issue because they have an extends, but with some assets like CSS or JS, is necesary reload AdminPlugins to force a deployment and propagate the changes.

Reading about http://php.net/manual/function.symlink.php seems that works also on Windows from Windows Vista/Windows Server 2008 or higher.

Can be possible replace this line:

https://github.com/NeoRazorX/facturascripts/blob/1c830a35c6980c7349858f7dfea4b7dbf5aad1f7/Core/Base/PluginDeploy.php#L208

with:

                \symlink($filePath, FS_FOLDER . DIRECTORY_SEPARATOR . 'Dinamic' . DIRECTORY_SEPARATOR . $folder . DIRECTORY_SEPARATOR . $fileName);

or, at least with debug enabled:

            if (\FS_DEBUG) {
                symlink($filePath, FS_FOLDER . DIRECTORY_SEPARATOR . 'Dinamic' . DIRECTORY_SEPARATOR . $folder . DIRECTORY_SEPARATOR . $fileName);
            } else {
                @copy($filePath, FS_FOLDER . DIRECTORY_SEPARATOR . 'Dinamic' . DIRECTORY_SEPARATOR . $folder . DIRECTORY_SEPARATOR . $fileName);
            }

I don't try if really works well on Windows, but seems to be tested by PHP team. With Linux in local works fine, and in linux servers is supposed that also works fine.

**Comment by NeoRazorX** [comment]
I'm sorry, I do not see any advantages.

**Comment by shawe** [comment]
@rsanjoseo @joenilson @RaulJJNazca @Cristoto y ahora mismo no recuerdo si me lo comentó alguien más.

Este "issue" estaba abierto porqué a mi me lo habíais comentado por privado "por verlo ilógico" y tener que estar cargando AdminPlugins para que se propague un cambio que se está haciendo en desarrollo porqué sin recargar la página no se hace deploy, y sin el deploy, no se propaga el cambio en ciertos archivos. Es una solución propuesta al inconveniente visto, pero sin que ninguno de los que en algún momento lo ha tenido como problema lo comente para que así se pueda valorar de otra forma. Si sólo 1 persona transmite este tipo de "trabas" y no se habla en general, las cosas no se aprecian como problema y como podéis ver se cierran por falta de participación.

Principalmente se sufre con los Assets, como ya me habéis comentado conmigo, principalmente con los CSS y JS cuando se están aplicando cambios para terminar de cuadrarlo al gusto.

Si realmente lo véis interesante/necesario, comentar aquí que es el lugar y las cosas se hablan entre todos.

@NeoRazorX las ventajas que indicas que no ves, como ejemplo, que el archivo no es necesario copiarlo constantemente si hay un symlink, ya que está accediendo al fichero real que le toca, y aplicando el cambio al fuente, este se propaga sin deploy a la versión en uso (por eso indiqué que como mínimo es interesante en desarrollo, en producción puede llegar a ser hasta contraproducente sin probarlo a fondo que en general no de problemas). Ya que por lo menos en desarrollo, es donde va a poder sufrir más cambios, y de este modo nos ahorramos el copiado constante que para este caso con este cambio menor agiliza el testeo sin tener que estar haciendo un paso adicional (aunque chorra) recargando AdminPlugins para que propague los cambios, con archivos que incluso puede que no se hayan modificado pero se están recreando en toda la carpeta constantemente, hasta que se da por bueno el cambio concreto que se estuviera haciendo.

**Comment by rsanjoseo** [comment]
Para el desarrollo si es un problema que a veces, los cambios no se vean reflejados hasta que no actualizas.
Desconozco el funcionamiento interno de ese apartado, pero si que me ha pasado de haber realizado cambios en un plugin y no ver los resultados porque no se había ejecutado Wizard y/o recargado AdminPlugins.
Eso puede hacer perder bastante tiempo.
Supongo que quién ya conoce el funcionamiento a fondo y sabe qué hacer en cada momento no encuentra ese problema, pero si se desea abrir la comunidad a nuevos desarrolladores, el tema puede resultar frustrante.

**Comment by Cristoto** [comment]
Al igual que @rsanjoseo desconozco al 100% como trabaja internamente facturascripts en ese caso, pero si que es bastante tedioso que cuando modificas un plugin, te esté dando problemas con el AdminPlugins porque no propaga bien los cambios e incluso he estado bloqueado bastante tiempo, porque no habia forma de verlos.

La idea de los "symlink" me parece bastante interesante porque no hay necesidad de copiar los archivos, si directamente puedes acceder a ellos de una forma directa.

**Comment by Cristoto** [comment]
He estado probando la mejora con el symlink y en windows 10 funciona correctamente, pero con la pega de que el servidor debe iniciarse como administrador.
Si el servidor no se inicia como administrador devuelve "warnings" indicando que no se pudo crear los symlinks.

**Comment by joenilson** [comment]
La idea del symlink es una aproximación para resolver un problema que tenemos actualmente, la otra aproximación que debemos hacer es utilizando la debugbar agregar un profiler o agregar más puntos de DataCollector en las llamadas internas que hace el núcleo de FS.

Las pruebas que realizó @shawe en Linux y yo en Mac fueron en ambientes de desarrollo controlados, aún no se han hecho pruebas con sistemas en hostings compartidos (shared hostings) y en equipos con controles de apache más estrictos.

Algo que nos ayudará mucho es agregar el profiler para twig en el phpdebugbar pero veo que actualmente están trabajando con un bug en el mismo y adicional a esto agregar el profiler a la cadena de llamadas en cada Controller y así tener una mejor visibilidad de en que punto estamos teniendo un exceso de llamadas o rellamadas a funciones que pueden estar dando lugar a las activaciones de plugins con problemas en la actualización de los assets.

Propongo que como paso inicial agreguemos puntos de DataCollection en los Controllers de FS, y luego como resultado de este proceso decidir si u symlink, un copy o uso de webpack o Encore nos vendría mejor para hacer robusto el deploy de plugins.
