### ISSUE TITLE
Nueva denominación de la moneda en Perú

### ISSUE THREAD

**Issue by victorze** [NeoRazorX/facturascripts#521]
Se cambió de la denominación “Nuevo Sol” a “Sol” y se dispuso el cambio del signo de "S/." a "S/"
[Mas información al respecto](http://www.bcrp.gob.pe/billetes-y-monedas/unidades-monetarias/sol.html).

https://github.com/NeoRazorX/facturascripts/blob/76f2e32f48e0cbb986e2e8f22699a5c5a961f864/Core/Data/Lang/ES/divisas.csv#L11

**Comment by shawe** [comment]
Esto más que ser un issue, debería ser una petición en un PR, no?
