### ISSUE TITLE
Use english for general in project

### ISSUE THREAD

**Issue by shakaran** [NeoRazorX/facturascripts#67]
I am native spanish like you, but if you use spanish in naming code, comments, or "hard" strings not localized, you are limiting your project internationally, without possibility that great programmers in Spain or outside speaking only english help in your project. Further, if someone wants forks the program in future for support other countries would be difficult since it will have to translate all the code.

Since this a initial rewrite, I purpose make this well from the start. Bonus, you will improve your english with the time ;)

**Comment by shawe** [comment]
I'm completely agree with you, but a lot of time, this is the hardest part to do ;)

**Comment by Yopli2k** [comment]
@shakaran Hola, al margen de la proposición, que puede ser mejor o no, yo tengo otra pregunta ... si eres nativo de habla castellana ¿ por qué escribes en lengua inglesa en un proyecto español ? ¿ Para los "grandes programadores en España o de fuera que sólo hablan inglés ?

**Comment by shakaran** [comment]
@Yopli2k dime, si fueras ruso o chino, aunque el proyecto fuera dirigido solo a personas de rusia o china. Querrías el código en ruso o chino? O te ayudaría el que estuviera en ingles, para contribuir, mejorar, etc? El ingles es como el esperanto del código en programación, me sabe hasta mal que tenga que explicar esto, con todas las recomendaciones que hay en Google. 

El ejemplo que pones a la inversa, nunca se va a dar, porque no te aceptarían cambiar a Español o escribir sugerencias en español (aunque pasa, por ejemplo proyectos en steam, de hoygans latinos pidiendo ayuda), por mucho que la población sea creciente a la de habla inglesa. 

Es tan simple, como que los números árabes se hicieron de facto, y se abandono el uso general de los números romanos. Si tu quieres imponer los números romanos (español), por facilidad, comodidad, whatever reason, nunca sera aceptado igual que si usas números arábigos (ingles).

@shawe el refactor o renaming ahora, es menos costoso en tiempo y difícil que cuando pasen unos meses u años

**Comment by Yopli2k** [comment]
@shakaran No te he preguntado eso, y no he puesto en duda en ningún momento tu argumentación sobre la propuesta.

**Comment by shakaran** [comment]
@Yopli2k sobre escribir este issue inicialmente en ingles es:
1) Recalcar mas la necesidad de hacerlo en ingles dando ejemplo
2) Al ser la petición de origen, que sirviera de precedente inicial para continuar cualquier issue o PR en ingles

**Comment by Yopli2k** [comment]
@shakaran  Hola, en la última reunión técnica, en Madrid, se acordó mirar de ir migrando y desarrollando lo nuevo con el inglés como base.

**Comment by shakaran** [comment]
@Yopli2k me parece una idea muy acertada para la beta que tenéis a partir de diciembre :) Saludos

**Comment by NeoRazorX** [comment]
Comments on the code and documentation are now in English.

**Comment by shawe** [comment]
It only remains to translate the contents of the folder Model and maybe some missing strings that we don't see while translating the content ;)

**Comment by Yopli2k** [comment]
Since the change to English has been decided and the appropriate measures taken, perhaps it is time to close this issue.
